services:
  auth-service:
    container_name: auth-service
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: auth-service-img
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    env_file:
      - .env
    command: ["npm", "run", "dev"]
    depends_on:
      - db
      - cache

  db:
    container_name: auth-db
    image: postgres
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: authdb
    volumes:
      - authdb-data:/var/lib/postgresql/data

  cache:
    container_name: auth-cache
    image: redis:8-alpine
    ports:
      - "6379:6379"
    volumes:
      - cache-data:/data

volumes:
  authdb-data:
  cache-data:
