services:
  user-service:
    container_name: user-service
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: user-service-img
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3002:3002"
    env_file:
      - .env
    command: ["npm", "run", "dev"]
    depends_on:
      - db
      - cache

  db:
    container_name: user-db
    image: postgres
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: userdb
    volumes:
      - userdb-data:/var/lib/postgresql/data

  cache:
    container_name: user-cache
    image: redis:8-alpine
    ports:
      - "6379:6379"
    volumes:
      - cache-data:/data

volumes:
  userdb-data:
  cache-data:
