name: Task Service CI/CD

on:
  push:
    paths:
      - "server/task-service/**"
    branches:
      - "task-service"
  pull_request:
    paths:
      - "server/task-service/**"
    branches:
      - "task-service"

jobs:
  test:
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install Dependancies
        run: npm ci
        working-directory: server/task-service

      - name: Run tests
        run: npm test || echo "No tests found, would add tests in a real project"
        working-directory: server/task-service
